### ISSUE TITLE
toc 기능 추가 부탁드려도 될까요?!

### ISSUE THREAD

**Issue by progresivoJS** [HyunSeob/hexo-theme-overdose#10]
말그대로 toc기능입니다.!!

[toc](https://github.com/bubkoo/hexo-toc)
여기 이 플러그인을 가져다 써봤는데, toc기능이 되긴 되는데

홈페이지에서 각 post에 대한 미리보기 있지않습니까

그 미리보기에서 글이 완전 깨져서 나오더라구요.

overdose 테마의 excerpt 기능과 호환이 안되는 느낌이었습니다.

저 뿐만 아니라 앞으로 이 theme을 이용하는 사람들이 많이 필요로 하는 기능일거같아요 ! 

항상 감사합니다 :+1:

**Comment by HyunSeob** [comment]
@progresivoJS
네 일단 확인해보고 다시 말씀드릴게요!

**Comment by HyunSeob** [comment]
@progresivoJS 
보니까 왜인지 모르겠으나 `content`가 전부 encode 되어있더라구요. 그래서 그 부분만 핸들했습니다.
아무래도 제 테마 문제라기보단 아무래도 그 플러그인이 이부분을 고려하지 않는 것 같아요 ㅠ

**Comment by progresivoJS** [comment]
고쳐 졌나요? 

저는 여전히 
![2016-09-29 8 14 12](https://cloud.githubusercontent.com/assets/22091806/18935703/bb57522e-861c-11e6-8631-e202e7688a1c.png)

이렇게 뜨네요..!!

이 플러긴이랑 뭔가 안맞나봅니다 덜덜

**Comment by progresivoJS** [comment]
@HyunSeob  아 아닙니다. 제가 확인을 잘 못했네요 ^^ 감사합니다.
