### ISSUE TITLE
Awsome! What a favorite theme!

### ISSUE THREAD

**Issue by yeolwoosung** [HyunSeob/hexo-theme-overdose#22]
I have a question before using this theme!
When you write, are you using the footnote in markdown?

If so, how should I use it?
tell me how to use the footnotes!

Thank you so much for your efforts! :)

**Comment by HyunSeob** [comment]
@SungYeolWoo 
감사합니다! 혹시 한국 분이시라면 한국어로 답변드려도 될까요? 😄 

제가 쓰고 있는 현재 지원하고 있는 각주 플러그인은 [hexo-footnotes](https://github.com/LouisBarranqueiro/hexo-footnotes)라는 것인데요, 설치하고 그냥 사용하시면 되고요. 사용방법도 그리 어렵지 않습니다.

[hexo-renderer-markdown-it](https://github.com/celsomiranda/hexo-renderer-markdown-it) 이라는 플러그인도 각주를 지원하긴 하는데 이거 별로 추천드리지 않아요. 다른 본문 렌더링도 영향이 있어서..

써주셔서 감사합니다. 🙇  혹시 의문점이 해결되셨다면 이슈는 닫아주시면 고맙겠습니다.

**Comment by yeolwoosung** [comment]
@HyunSeob

아!! 이렇게 사용할 수 있군요!
이슈들을 영어로 등록하신 것 같아서! 영어로 남기고 싶어하신 줄 알았어요!! 

지킬, 고스트, 워드프레스 다 해봤지만 마땅히 마음에 드는게 없었는데 이번엔 너무 좋은 것 같습니다!
친절한 답변 감사합니다! 너무 잘 만드셨어요! 😄

**Comment by HyunSeob** [comment]
@SungYeolWoo 감사합니다 😀
