### ISSUE TITLE
질문이 있습니다!!!

### ISSUE THREAD

**Issue by yeolwoosung** [HyunSeob/hexo-theme-overdose#25]
안녕하세요! :)

code highlight를 다양하게 지원하게 해보고 싶어서 시간날때마다 이것저것 만져보고 있는데요!
혹시 scss에서 config 파일의 설정을 어떻게 불러올 수 있나요?

```scss
@import "overdose.scss";
@import "layout.scss";
@import "menu.scss";
@import "article.scss";
@import "sharer.scss";
@import "post-list.scss";
@import "pagination.scss";
@import "code.scss"; // here
@import "widgets.scss";
@import "footer.scss";
```

`here` 자리에  동적으로 import 하려고하는데...

scss에서는 hexo config 파일을 어떻게 불러올 수 있나요?

icarus는 stylus를 사용해서 그런지 모르겠지만 
```styl
highlight = hexo-config("customize.highlight") || "tomorrow"
```
이렇게 불러올 수 있더라구요! 
혹시 scss에서도 이렇게 불러올 수 있나요?? :)

**Comment by HyunSeob** [comment]
안녕하세요 😄 

Sass는 안타깝게도 Dynamic import가 안되는 걸로 알고 있습니다. 아래 링크에 정보가 나와있네요.
https://github.com/Compass/compass/issues/613

저도 예전에 그 문제 때문에 고민을 좀 해봤는데 CSS 묶는걸 포기하고 HTML head 블록에다가

``` jade
link(rel="stylesheet" href="/css/#{theme.config.highlight || 'dracular'}.css")
```

요렇게 해주면 가능은 할 것 같습니다.

코드 하이라이트 추가 끝나시면 PR도 날려주심 정말 감사하겠습니다! 🙇
