### ISSUE TITLE
코드 블럭에서 indent가 일정하지 않아요

### ISSUE THREAD

**Issue by juhojuho** [HyunSeob/hexo-theme-overdose#33]
안녕하세요~

한 가지 이상한 점이 있어 이슈 등록합니다.
![예시](https://cloud.githubusercontent.com/assets/20736846/24436087/5911c9aa-1474-11e7-89d0-9350ce755972.png)

global _config.yml에서 hightlight의 line_number를 true로 설정하면 위 사진처럼 코드를 쓸 때 앞 공간이 들쑥날쑥합니다. 다른 theme을 사용할 경우 문제없이 indent가 일정하게 나타나는 걸로 봐서 hexo 자체의 문제는 아닌 것 같습니다. 

항상 overdose theme 감사히 잘 쓰고 있습니다.
넘나 아름다운 theme이에요ㅠㅠ

**Comment by HyunSeob** [comment]
이슈 제보해주셔서 감사합니다! 문제점 부터 일단 파악해볼게요 😄

**Comment by HyunSeob** [comment]
@juhojuho 안녕하세요. 좀 늦어서 죄송합니다. 일단 수정은 했습니다. (코드블록이 실제로는 `<table>`이라서 발생한 이슈네요) master pull 받으시면 정상적으로 사용하실 수 있을 겁니다. 😀
