### ISSUE TITLE
theme 수정 관련하여 질문입니다.

### ISSUE THREAD

**Issue by mulder21c** [HyunSeob/hexo-theme-overdose#42]
안녕하세요 :)
theme 관련하여 몇 가지 수정 건에 대해 PR을 날리다가 
PR을 날려도 될지 혹은 그냥 개인 수정건으로 가지고 있어야 할지 애매한 부분이 있어서 질문 남깁니다 ^^;

다름이 아니라 어찌보면 검색엔진최적화와 웹 접근성에 연관되는 부분인데,
테마의 Document Outline 구조가 HTML 5 명세에 맞지 않는 상황이라,
제 블로그에는 연관되는 부분들을 수정하여 Heading 구조와 Document Outline 구조를 어느 정도 손봐두었는데,

일부 tag 구조 자체를 바꾸는 부분이다보니 (`<nav>` 요소를 `<div>`으로 변경, 가시적으로 숨겨진 heading 추가 등) 해당 부분을 수정하여 PR을 드려도 괜찮을지 여쭈어 봅니다 

아래는 현재 - 변경 이후 heading 구조들입니다.

인덱스 페이지

![the tracks of mulder21c](https://user-images.githubusercontent.com/14821565/28777741-605d0d30-7637-11e7-9f2e-63ef7ab890c9.png)

![the tracks of mulder21c 1](https://user-images.githubusercontent.com/14821565/28777740-605cea6c-7637-11e7-9529-26467088fd9e.png) 

포스트 페이지

![part 2 the tracks of mulder21c](https://user-images.githubusercontent.com/14821565/28777744-6060a9ea-7637-11e7-8952-1216793ce431.png)

![part 2 the tracks of mulder21c 1](https://user-images.githubusercontent.com/14821565/28777743-60601c78-7637-11e7-85d8-42fe98707be9.png)

**Comment by HyunSeob** [comment]
PR 주시면 정말 감사하죠! 일단 PR 주시면 기존에 주신 PR하고 더불어 검토해보고 적용하겠습니다.
저는 현재 bourbon 삭제 건으로 작업 중이니 실제 마스터 브랜치에 반영은 조금 느릴 수도 있어요.
