### ISSUE TITLE
index.css ERR_ABORTED

### ISSUE THREAD

**Issue by cmygray** [HyunSeob/hexo-theme-overdose#44]
index.html 의 스타일 소스가 index.css로 되어있어서 스타일 적용이 되지 않는 문제가 발생합니다.
public 폴더의 index.html 코드를 index.scss 로 수정해도 해결이 안되어서 막힌 상태입니다.

**Comment by cmygray** [comment]
여러가지 방법을 시도해봤는데, hexo-renderer-bourbon 설치가 문제인 것 같습니다.

**Comment by HyunSeob** [comment]
v1.0.0에서 문제가 해결됐는지 확인해보세요. 이제 bourbon에 디펜던시는 없습니다.
