### ISSUE TITLE
All images in article always have 100% width.

### ISSUE THREAD

**Issue by HyunSeob** [HyunSeob/hexo-theme-overdose#5]

**Comment by HyunSeob** [comment]
This issue closed by https://github.com/HyunSeob/hexo-theme-overdose/commit/2ecaaad3cf7ed13c80170002f9a5b3c93fc7ee3b

**Comment by progresivoJS** [comment]
이거 어떻게 해결하나요? 

[2ecaaad](https://github.com/HyunSeob/hexo-theme-overdose/commit/2ecaaad3cf7ed13c80170002f9a5b3c93fc7ee3b) 이거 보고 해봐도 안되네요..

(https://hyunseob.github.io/2016/03/27/usage-of-sequelize-js/) 여기에 나와있는 큐브 이미지 처럼 사이즈 작게 하려면 어떻게해야하나요?

저는 항상 100% width가 나오네요 .

**Comment by progresivoJS** [comment]
아,
[link](https://github.com/HyunSeob/hexo-theme-overdose/blob/2ecaaad3cf7ed13c80170002f9a5b3c93fc7ee3b/source/css/article.scss) 이 file 그대로 복붙했더니 해결됐어요 ! 감사합니다.

**Comment by HyunSeob** [comment]
@progresivoJS 그렇게 하시는 것보단 `git pull`을 받으시는 게 좋을 거에요!

**Comment by progresivoJS** [comment]
@HyunSeob 아 넵. 받은지 한 2~3일 된거같은데 계속해서 업데이트가 되네요. 기대가 많습니다 굿!
hexo theme 하나하나 다 찾아봤는데, 이 테마가 제일 중독성있는거같아요.ㅋㅋㅋ

역시 이름값하는 듯!

**Comment by HyunSeob** [comment]
@progresivoJS 허허 칭찬 감사합니닷!!
